print('Hello World')
print('This is a test script.')
print(5+8)
print('The result of 5 + 8 is:', 5 + 8)
print('India', 'USA', 'Canada')
print('India', 'USA', 'Canada', sep='-')
print('India', 'USA', 'Canada', end=' ')
print('are countries in the world.')
print('Hello', 2563, 1827.87, True, [1,3,5,7], ('ant', 'bat', 'cat'), {'name': 'John', 'age': 30}, None)